---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${database-url}/caelum_treinamentos?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/caelum_treinamentos?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


---
spring:
  profiles: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:caelum_treinamentos;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
