INSERT INTO course(code, description, duration) values('FJ-11', 'Object Orientation', 144000);
INSERT INTO course(code, description, duration) values('FJ-21', 'Java Web', 144000);
INSERT INTO course(code, description, duration) values('FJ-22', 'Spring, Test, Git & Maven', 72000);
INSERT INTO course(code, description, duration) values('FJ-25', 'Hibernate, JPA & EJB Lite', 144000);
INSERT INTO course(code, description, duration) values('FJ-26', 'JSF & Primefaces', 144000);
INSERT INTO course(code, description, duration) values('FJ-27', 'Spring Framework', 144000);
INSERT INTO course(code, description, duration) values('FJ-36', 'Integrations in Java', 144000);
INSERT INTO course(code, description, duration) values('FJ-37', 'Java EE', 216000);
INSERT INTO course(code, description, duration) values('FJ-87', 'Agile Practices', 72000);
INSERT INTO course(code, description, duration) values('FJ-91', 'Java Architecture', 144000);